version: '3'

services:
  db:
    image: postgres:latest 
    environment:
      POSTGRES_DB: app_manager
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      - DJANGO_SUPERUSER_USERNAME=your_username
      - DJANGO_SUPERUSER_EMAIL=your_email@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=your_password

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web
