# Generated by Django 4.2.6 on 2023-10-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_manager.app'),
        ),
    ]
