# Generated by Django 4.2.6 on 2023-10-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0002_remove_app_subscription_alter_subscription_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='free', max_length=100),
        ),
    ]
